apiVersion: deployment.krateo.io/v1alpha1
kind: FireworksApp
metadata:
  creationTimestamp: "2024-05-02T07:11:46Z"
  labels:
    crossplane.io/composite: firefire-fireworksapp
  name: firefire-fireworksapp
  uid: 977cc4a9-6e6a-4bca-82e3-9959f9cebd9c
spec:
  compositionRef:
    name: fireworksapp.deployment.krateo.io
  compositionRevisionRef:
    name: fireworksapp.deployment.krateo.io-509bdb5
  compositionUpdatePolicy: Automatic
  description: Fireworks App Deployment
  flat:
    destinationEndpoint: github
    host: fireworks-app.krateo.site
    name: firefire
    organizationName: krateoplatformops-archive
    replicas: 3
  icon: fa-solid fa-fire
  links:
  - icon: fa-brands fa-git
    title: krateoplatformops-archive/krateo-fire-firefire
    url: https://github.com/krateoplatformops-archive/krateo-fire-firefire
  owner: mauro
  plugins:
  - endpointName: argocd
    icon: fa-solid fa-diagram-project
    name: resources
    type: argocd
    value: firefire-fireworksapp
  - endpointName: github
    icon: fa-solid fa-book
    name: documentation
    type: doc
    values:
    - '[krateoplatformops-archive][krateo-fire-firefire]README.md'
  - icon: fa-brands fa-docker
    name: kubernetes
    type: kubernetes
    value: deploymentId
  - endpointName: github
    icon: fa-solid fa-person-running
    name: pipelines
    type: pipeline
    values:
    - '[krateoplatformops-archive][krateo-fire-firefire]Build Docker image for every
      commit'
  resourceRefs:
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: ProviderConfig
    name: firefire-fireworksapp-provider-k8s-pc-in
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: firefire-fireworksapp-argocd-app-object
  - apiVersion: git.krateo.io/v1alpha1
    kind: ProviderConfig
    name: firefire-fireworksapp-provider-git-pc
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: firefire-fireworksapp-fireworksapp-values
  - apiVersion: git.krateo.io/v1alpha1
    kind: Repo
    name: firefire-fireworksapp-7wgn9
  - apiVersion: github.krateo.io/v1alpha1
    kind: ProviderConfig
    name: firefire-fireworksapp-provider-github-pc
  - apiVersion: github.krateo.io/v1alpha1
    kind: Repo
    name: firefire-fireworksapp-cl68q
  tags:
  - fireworks
  - template
  - krateo
  - katy perry
  templateName: krateo-fireworks
  title: firefire
  values:
    endpointName: github
    fromRepo:
      organizationName: krateoplatformops
      repositoryName: krateo-template-fireworksapp
      schema: https
    host: fireworks-app.krateo.site
    namespace: krateo-system
    organizationName: krateoplatformops-archive
    replicas: 3
    repositoryName: krateo-fire-firefire
    toRepo:
      organizationName: krateoplatformops-archive
      repositoryName: krateo-fire-firefire
      schema: https
